### PR TITLE
Algorithms with JavaScript

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
- [x] I have checked that this is not a duplicate problem
- [x] My Code is in running state
- [x] I have read the README.md file 
- [x] I have starred the repo. 
### Description of Change

- [x] My change is a new addition.

### File Changes
* [x] Sorting
  * [x] Comb Sort
  * [x] Heap Sort
  * [x] Insertion Sort
  * [x] Quick Sort
  * [x] Radix Sort
* [x] Searching
  * [x] Binary Search
* [x] Graph
  * [x] Dijkstra Algorithm

### CODE REVIEW

**Comment by vyasriday** [comment]
@Siddhant-K-code Are you going to add all by yourself. 😅 Thanks for contributing though :)

**Comment by Siddhant-K-code** [comment]
Yes, these are very basic except two, i took help from other sources too.

**Comment by vyasriday** [comment]
Merged!

**Comment by Siddhant-K-code** [comment]
pls add `hacktoberfest-accepted` badge, so my PR can eligible for Hacktoberfest, accr. to new guidelines

**Comment by vyasriday** [comment]
You PR is merged so it's eligible for hacktoberfest. Also repo contains hacktoberfest label so it's part of hacktoberfest anyway. :)

**Pull request merged**
