### PR TITLE
Add printStar.js for issue #16

### PR DESCRIPTION
**Pull request by yanagiragi**

### CODE REVIEW

**Comment by Reynadi531** [comment]
To simplify, you can do this:
`
for(let i=1; i<=n; i++){
   console.log("*".repeat(i));
}
`
Here some docs for repeat function:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

**Comment by vyasriday** [comment]
@Reynadi531 Please add your solution as well in `/problems/starPattern.js` and raise a PR for the same.

**Review by vyasriday — CHANGES_REQUESTED** [review]
Could you please move this solution to the file mentioned in the comments.

**Review by yanagiragi — COMMENTED** [review]
LGTM

**Comment by yanagiragi** [comment]
Simplify issue and path issue fixed.

**Comment by Reynadi531** [comment]
Heres my PR thank you 😊 #19

**Comment by vyasriday** [comment]
@yanagiragi Since @Reynadi531 already created a PR with his solution. you can add your solution in the same file.

**Comment by yanagiragi** [comment]
> 
> 
> @yanagiragi Since @Reynadi531 already created a PR with his solution. you can add your solution in the same file.

Does the "same file" mean to rename 'problems/printStar' to 'src/problems/starPattern.js'?

BTW, it seems our code are almost likely to be same logic. To avoid similar logic exists in same code, perhaps I can close the PR and use @Reynadi531 's version instead?

**Comment by vyasriday** [comment]
@yanagiragi Do not rename it. just add your code as well in the same file if your code is different than the ones exists. Use https://github.com/vyasriday/JS-Tidbits/blob/master/src/problems/stringReversal.js for reference.

**Comment by yanagiragi** [comment]
Done. However I had to remind you that currently my solution is placed at '/problems/printStar.js' instead of '/src/problems/printStar.js' due to this [comment](https://github.com/vyasriday/JS-Tidbits/pull/17#issuecomment-699386865), which I think is kind of weird since it does not follow other files in your repo.

**Comment by vyasriday** [comment]
Looks like my bad. I meant that inside src. Didn't notice that.

**Review by vyasriday — APPROVED** [review]

**Pull request merged**
